INSERT ALL
    INTO CLIENTE (ID, NOME) VALUES (21856,'Jar Jar Binks')
    INTO CLIENTE (ID, NOME) VALUES (39550,'R2D2')
    INTO CLIENTE (ID, NOME) VALUES (44993,'C-3PO')
    INTO CLIENTE (ID, NOME) VALUES (49400,'Jabba the Hutt')
SELECT * FROM dual;